// admin/src/views/permission/role/permission.vue
<template>
  <c-layout-form @submit="handleSubmit" v-if="!loading">
    <a-card title="分配权限">
      <a-space :size="20" direction="vertical">
        <a-space direction="vertical" v-for="(item, index) in data" :key="index">
          <div>{{ item.name }}</div>
          <a-space direction="vertical" v-if="item.type === MenuTypeEnum.module">
            <div>{{ item.name }}</div>
            <a-checkbox-group v-model:value="item.checked" :options="item.children" :disabled="isDisabled" />
          </a-space>
          <a-checkbox-group v-model:value="item.checked" :options="item.children" :disabled="isDisabled" v-else />
        </a-space>
      </a-space>
    </a-card>
  </c-layout-form>
</template>
<script lang="ts" setup>
import { roleApi, rolePermissionApi, menuApi } from '@/api/permission'
import type { PermissionName } from '@/api/types'
import { MenuTypeEnum } from '../enums'

const { id } = useRoute().params
const isDisabled = ref(false)

const getRolePermission = (list: PermissionName.MenuDataType[], permissions: string[], reduce?: string) =>
  list.map(item => {
    if (item.type === MenuTypeEnum.action) {
      item.value = reduce + item.content
      item.label = item.name
    } else if (item.children?.length) {
      item.children = getRolePermission(item.children, permissions, reduce + (reduce ? ':' : '') + item.content)
      if (item.type === MenuTypeEnum.page) {
        let checked = item.children
        !permissions.includes('*') && (checked = checked.filter(({ value }) => permissions.includes(`${reduce}:${value}`)))
        item.checked = checked.map(({ value }) => value)
      }
    }
    return item
  })

const { data, loading } = useApiRequest<PermissionName.GroupMenuRole[]>(async () => {
  const [roleRes, menuRes] = await Promise.all([roleApi.get<PermissionName.RoleDataType>(+id), menuApi.all<PermissionName.MenuDataType>()])
  isDisabled.value = roleRes.permissions.includes('*')
  const options = getRolePermission(menuRes, roleRes.permissions)
  console.log(options)
  return options
})

const handleSubmit = () => {}
</script>

// admin/src/views/setting/role/permission.tsx
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Card, Descriptions, Checkbox, Button, Space } from 'antd'
import { ArrowLeftOutlined } from '@ant-design/icons'
import { allPermission } from '@/config/sidebar'
import { roleApi } from '@/api/role'
import type { DataType } from './types'
import Styles from './permission.module.less'

export default function RolePermissionPage() {
  const navigate = useNavigate()
  const { id } = useParams()
  const [permission, setPermission] = useState<string[]>([])
  const loadData = async () => {
    const data = await roleApi.get<DataType>(+id!)
    setPermission(data.permissions)
  }
  useEffect(() => {
    loadData()
  }, [])

  return (
    <Card title="角色权限详情">
      <Space direction="vertical" size={100}>
        <div>
          {allPermission.map(module => (
            <Descriptions key={module.value} title={module.label} column={1} size="default" className={Styles['custom-description']}>
              {module.children?.map(page =>
                page.hidden ? null : (
                  <Descriptions.Item label={page.label} key={page.value} labelStyle={{ color: 'rgba(0,0,0,0.85)' }}>
                    {page.children?.map(item => (
                      <Checkbox key={item.value} checked={permission.includes('*') || permission.includes(item?.value)}>
                        {item?.label}
                      </Checkbox>
                    ))}
                  </Descriptions.Item>
                )
              )}
            </Descriptions>
          ))}
        </div>
        <Button icon={<ArrowLeftOutlined />} onClick={() => navigate(-1)}>
          返回
        </Button>
      </Space>
    </Card>
  )
}
