// admin/src/views/auth/register.vue
<template>
  <div class="w-screen h-screen bg-radial flex justify-center items-center relative">
    <div class="absolute top-50 left-50">
      <a-image src="/logo.svg" :width="60" :preview="false" />
    </div>
    <a-card title="注册" class="w-320">
      <a-form>
        <a-form-item>
          <a-input v-model:value="formState.username" placeholder="请输入4-16位数字、字母或特殊字符的账号" />
        </a-form-item>
        <a-form-item>
          <a-input-password v-model:value="formState.password" placeholder="请输入密码" />
        </a-form-item>
        <a-form-item>
          <a-input-password v-model:value="formState.cpassword" placeholder="请输入确认密码" />
        </a-form-item>
        <a-form-item>
          <a-button type="primary" block @click="handleSubmit">注册</a-button>
        </a-form-item>
      </a-form>
      <router-link to="/login" class="text-center text-info">已有账号，去登录</router-link>
    </a-card>
  </div>
  <c-captcha v-model:visible="showCaptcha" v-model="formState.code" @success="handleSubmit" />
</template>
<script setup lang="ts">
import { message } from 'ant-design-vue'
import { registerApi } from '@/api/auth'

const router = useRouter()
const showCaptcha = ref(false)

const { formState, setFormStateRules, validFormState } = useFormState({
  username: '15575148487',
  password: '123456',
  cpassword: '123456',
  code: null
})

setFormStateRules({
  username: {
    validator(value: string) {
      if (!/^[a-zA-Z0-9_-]{4,16}$/.test(value)) return Promise.reject('账号格式错误')
      return Promise.resolve()
    }
  },
  password: { required: true, message: '请输入密码', },
  cpassword: {
    validator(value: string) {
      if (value !== formState.value.password) return Promise.reject('确认密码和密码不一致')
      return Promise.resolve()
    }
  }
})

/**
 * 提交
 */
const handleSubmit = async () => {
  if (!(await validFormState())) return
  if (!formState.value.code) {
    showCaptcha.value = true
    return
  }

  try {
    await registerApi.post<UserInfo>(formState.value)
    message.success('注册成功，请登录')
    router.push({ name: 'login' })
  } catch {
    formState.value.code = null
  }
}
</script>

// admin/src/views/auth/register.tsx
import { Button, Card, Form, Input, message } from 'antd'
import { LockOutlined, UserOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import { registerApi } from '@/api/auth'
import styles from './register.module.less'

export default function RegisterPage() {
  const navigate = useNavigate()
  const [form] = Form.useForm()

  const onFinish = async (values: Record<string, unknown>) => {
    await registerApi.post(values)
    message.success('注册成功')
    navigate('/login')
  }

  const formProps = {
    labelCol: { span: 0 },
    wrapperCol: { span: 24 },
    onFinish,
    form,
    initialValues: { remember: true }
  }

  const onLogin = () => {
    navigate('/login')
  }

  return (
    <div className={`${styles.wrap} w-vw h-vh flex flex-center hidden p-0`}>
      <Card title="注册" style={{ width: 380 }}>
        <Form {...formProps}>
          <Form.Item name="phoneNumber" rules={[{ required: true, message: '请输入手机号码' }]}>
            <Input prefix={<UserOutlined className="color-25" />} placeholder="请输入手机号码" allowClear />
          </Form.Item>
          <Form.Item name="password" rules={[{ required: true, message: '请输入密码' }]}>
            <Input.Password prefix={<LockOutlined className="color-25" />} placeholder="请输入密码" allowClear />
          </Form.Item>
          <Form.Item
            name="cPassword"
            rules={[
              {
                required: true,
                validator: (_, value) => {
                  if (value !== form.getFieldValue('password')) return Promise.reject(new Error('两次输入密码不一致'))
                  return Promise.resolve()
                }
              }
            ]}
          >
            <Input.Password prefix={<LockOutlined className="color-25" />} placeholder="请再次输入密码" allowClear />
          </Form.Item>
          <Form.Item>
            <Button type="primary" htmlType="submit" block>
              注册
            </Button>
          </Form.Item>
          <Form.Item>
            已有账号,
            <Button type="link" onClick={onLogin}>
              去登录
            </Button>
          </Form.Item>
        </Form>
      </Card>
    </div>
  )
}
